name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17.0.14
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.14'
          architecture: x64

      - name: Set up Maven 3.8.7
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
          tar -xzf apache-maven-3.8.7-bin.tar.gz
          echo "$GITHUB_WORKSPACE/apache-maven-3.8.7/bin" >> $GITHUB_PATH
          mvn --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
