name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Maven 3.8.7 from apt
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn --version

      - name: Set up JDK 17.0.14
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.14'
          architecture: x64

      - name: Build with Maven
        run: |
          cd status-checker
          mvn -B package

      - name: Run tests
        run: |
          cd status-checker
          mvn test
